name: Deploy Weather API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
  cd /home/ec2-user/Weather-API || exit

  # Fix ownership
  sudo chown -R ec2-user:ec2-user /home/ec2-user/Weather-API

  # Fix Git safe directory
  git config --global --add safe.directory /home/ec2-user/Weather-API

  # Pull latest changes
  git reset --hard
  git pull origin main

  # Install Node.js if missing
  if ! command -v node &> /dev/null; then
    curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
    sudo yum install -y nodejs
  fi

  # Install dependencies
  npm install

  # Kill existing server if running on same port
  fuser -k 4000/tcp || true

  # Start server in background using nohup
  nohup node server.js > server.log 2>&1 &

