name: Deploy Weather API to EC2 with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Navigate to project directory
            cd /home/ec2-user/Weather-API || exit

            # Fix ownership and Git safe directory
            sudo chown -R ec2-user:ec2-user /home/ec2-user/Weather-API
            git config --global --add safe.directory /home/ec2-user/Weather-API

            # Pull latest changes
            git reset --hard
            git pull origin main

            # Install Node.js if missing
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Install PM2 if missing
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Install project dependencies
            npm install

            # Start or restart server with PM2
            pm2 start server.js --name weather-api || pm2 restart weather-api

            # Save PM2 process list for auto-start on reboot
            pm2 save
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ec2-user --hp /home/ec2-user

            # Show running Node processes for verification
            pm2 list

